title:            Takehiro Adachi
description:
url:              http://take.github.io
signoff:          Takehiro Adachi
disqus_shortname: takehiroadachi # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Talks
    url:          /talks
  - name:         Ja Posts
    url:          /ja
  - name:         Email
    url:          mailto:takehiro0740@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/take
    external:     true
  - name:         Twitter
    url:          https://twitter.com/takehiro0740
    external:     true

pygments:         true
permalink:        /:categories/:title
markdown:         kramdown
rdiscount:
  extensions:     [smart]
